### ISSUE TITLE
若干格式问题

### ISSUE THREAD

**Issue by qnomad** [MobtgZhang/sues-thesis#11]
Hi

封面论文标题的上部空白间距貌似太小了。另外，原创性声明也应加粗？

**Comment by MobtgZhang** [comment]
论文封面标题可以通过suesthesis.cfg 调整空白间距，原创性声明我更改一下，这两个即将更改

**Comment by MobtgZhang** [comment]
> Hi
> 
> 封面论文标题的上部空白间距貌似太小了。另外，原创性声明也应加粗？

基本解决了
